{
 "title": "FoodToSave-Case",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/081d39a1-prod-clientsapiin-6e48/c70081e3c5e9d373"
     },
     "expr": "sum(rate(request_duration_seconds_count{job=\"foodtosave-case\"}[1m])) * 60",
     "legendFormat": "__auto",
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "period": "1m",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/081d39a1-prod-clientsapiin-6e48/c70081e3c5e9d373"
     },
     "expr": "histogram_quantile(0.90, sum(rate(request_duration_seconds_bucket{job=\"foodtosave-case\"}[1m])) by (le)) /1000",
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "period": "1m",
     "region": "us-east-1",
     "statistic": "p95"
    }
   ]
  },
  {
   "title": "Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{job=\"foodtosave-case\"}[1m])) by (le)) / 1000",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{job=\"foodtosave-case\"}[1m])) by (le)) / 1000",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(request_duration_seconds_bucket{job=\"foodtosave-case\"}[1m])) by (le)) / 1000",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(request_duration_seconds_bucket{job=\"foodtosave-case\"}[1m])) by (le)) / 1000",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_duration_seconds_bucket{job=\"foodtosave-case\"}[1m])) by (le)) / 1000",
     "legendFormat": "Median"
    },
    {
     "expr": "(sum(rate(request_duration_seconds_sum{job=\"foodtosave-case\"}[1m]))\n/\nsum(rate(request_duration_seconds_count{job=\"tfoodtosave-case\"}[1m]))) / 1000",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Count Total Redis Errors",
   "type": "timeseries",
   "description": "in de last minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_errors_total{job=\"foodtosave-case\", code_error=\"RC-404\"}[1m])) by(code_error)",
     "legendFormat": "{{code_error}}"
    }
   ]
  },
  {
   "title": "Request Count by Status",
   "type": "timeseries",
   "description": "in de last minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(request_duration_seconds_count{job=\"foodtosave-case\"}[1m])) by (status_code, router)) * 60",
     "legendFormat": "{{ status_code }} {{router }}"
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  }
 ]
}